language: objective-c
osx_image: xcode7.2
xcode_project: TravisTest.xcodeproj
xcode_scheme: TravisTest
xcode_sdk: iphonesimulator9.2
before_install:
- brew update
- brew upgrade xctool
env:
  global:
  - secure: T2sOJicybh2+sGmtXKwSFJrciXFTz1d1DBK5zBrW/rpJzAyix3TA6kA1ZCt5K5pOwW4VDNY4BaxhLzVlTVrDEfBaid8hpnMuUCCO1I5PoHvD8sI1YtPxcYrj+Q5bI/QVMClMoNJ/pqCm0/J39bookqyOolBoi+/5KGrFRAlztt6UGSGM3f+mnXa9TqzVc4kD4jHAJqdilhHKkrfsT9TwzIYnWefszyNFC7OIVC3KlImdjnQcE1YT1CdwDSF/6K3+3Cz1VwfJXG76a1vWMKfxQYzwhD/MUJ9fnNw9ahBpqguSDCKnxgExBDxGQk3KzWBbhVGHn9qikAgJzi1LF1k2BNL0qTxaMnvHtterqusNnH6A4YFSvJXNFpN69DU3NPIqLQOMmPupAw51HNQGelf0rc2h1oXOcrzkodKUEkbOFtb+KaV/vs6aoTn8s6HHqDCfV8t2tCaEYzGWdYHAPYKhSm76aSI4xFCT1DCjdZLjT8UL1s4QPxn/XVvh5mv476iQpF2VNpUAkal6MZQxl4vJrUm7aVXEhljDiLbBOVU+ki2xCr8XsDSLAYRSsJ3Sh4m1VqovEx7X8/aHueqIr+xfQgKaRRizsN1n/qosije+0+4V0N0jGzPwbBkLQj/zswQqg11PWwX6tlAJA9pRVG8G0h7nKW+wkaLurX+qRJ5fL0A=
  - secure: JT0Hj7BTx0Qq118SvvwzxAgMVZyVJz7zDdnFbAQQNi7VTy4CCqL7W6yPTZtwujU/VgBR9dH7vHYt2e4y/9QsNjMcaxkrubCD/UOPWYc0bNlbfgIBSvvkF2ya8D1cnpmgTiLaflUVKtVfZvGNKGJBw7VgyjiKGqL0oomVApObHtuhX0vD1JyAQ1ci8DfggkNpD1a62LVdWm2UjcRYdU9f5v5MV9J8LB2/VoYlFVq/u6ThPcxRD5ATvj2M/C+wqGRzq+6g06mMoNXg0Un9teBGCfI3VTLrlm7oWq2o9Ok+JNByB7HNveIoGH5xSDs3kc/LmZW+dm+FqoMo1MFizY5E1SpwkB6QE/mY+817tWtLR+ekhFecdTNDM0sbvl9cLepdbebKvdhgvPuEbnYtTgAhAzyNjAoMD/KaSrjmratqJD5DFgEVU3aiMXfQZYfJ811QnBawo7fEiPdKn5DM+xvXO2XyxaCzF9KBt5pMipA+OeiFaWabwskWQqAE2ji/5BT/Va6SMSvw1HeL13UgkWpma7pvV9euU6sdLIH9ksFbsydDbscA/F/i3raHlYW49f016xsz26i8Y+VSI+RuaSnBTaGi8fZxc+Fu1X5hwln79/oDaHF1FiPdcW0oxQJ3WvykvsUkX7r6qtsu/RthSzVdyWOBELYssYchFbEpgCO+MHQ=
  - APP_NAME="TravisTest"
  - 'DEVELOPER_NAME="iPhone Distribution: Michael Updegraff (R296M65L64)"'
  - INFO_PLIST= "TravisTest/Info.plist"
  - BUNDLE_DISPLAY_NAME="io.upworks.TravisTest"
  - PROFILE_NAME="TravisTest_Ad_Hoc"
  - GOOD_ZIP="Good_Dynamics_client_SDK_for_iOS_v2.1.4439.tar.gz"
  - FIPS_FILE="FIPS_module.tar"
  - FIPS_DIR="FIP_Module"
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisTest_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/TravisTest_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
- cp "./scripts/$GOOD_ZIP" /Applications/Xcode.app/Contents/Developer
- cd /Applications/Xcode.app/Contents/Developer
- tar zxvf Good_Dynamics_client_SDK_for_iOS_v2.1.4439.tar.gz
- cd ./Good.Platform
- mkdir "$FIPS_DIR"
- cp "$FIPS_FILE" ./"$FIPS_DIR"
- cd ./"$FIPS_DIR"
- tar zxvf "$FIPS_FILE"
- cd /Applications/Xcode.app/Contents/Developer/Good.Platform
- sudo ./install.sh
- cd /Users/travis/build/UpWorks/TravisTest
- ./scripts/cs-xproj-validate.sh
script:
- xctool test -project TravisTest.xcodeproj -scheme TravisTest -sdk iphonesimulator9.2
  ONLY_ACTIVE_ARCH=NO
- xctool -project TravisTest.xcodeproj -scheme TravisTest -sdk iphoneos9.2  -configuration
  Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
before_deploy:
- echo "deploying  Travis Build $TRAVIS_BUILD_NUMBER to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: kSJkB+sdJI9P0GoLS9SPSNRedmmcSdOMdNMicqitpKyYhL1EqS3FTe2mewkdScNlEKYpluT+zaS7dVlHpfY+k2xZGN1GLVGUfmEEpqkuFUP/yepItgc48q0+dzL2Boq2fS32PxNE5v6tynIHQCEvYUDNTXIzzEh+ZOUuDFjes5m9CCkFXLZ+JtTa4PEwHFeHpOUKs14PE2jBe5qNymoUcRugNqpIO9X6AJh7y2e1FpzdW7p68gEydisZyQWWE1S6hfglzzARZ6x/5DzXM7+BafatVte8I2HsKx5ja9vNycTjRqTRaMbID03YiqQeNwoB5S+oeVAjCn4ZeWhnJVLIv3twKVldT2Z5GhAPH/3HUU2eZnftkhPJWNZ0hwmsycP2EsQXa63EyaG7OCQBvZAmlE1q3U69k0zNnskwrjF6vCa7lSlHMX+OcyFVtlIIkXieQCOFtQLS0V0SXYjh8DFib6zqG07OS/yO73Kad/ktwDPpRS5QbN05wkn/KcuTps9K1Qgq9Ni82TUjxt0//z/cRK23egzOA/gbAl65e33XL8/uCtlLL+dqTIPC8KXLOok6pSVEmQazreq2TugeW6emYcK/zGNUT47h9lEInHC6C3Fm4NrhsvCOUlUVmP6ALpjRvTFr01w1V5IKS1k7cdnj2BNukuikFiNEpJcu2d0BFE8=
  file: /Users/travis/build/UpWorks/TravisTest/build/Release-iphoneos/TravisTest.app.*.dSYM.zip
  skip_cleanup: true
  on:
    repo: UpWorks/TravisTest
